---
- import_playbook: common.yml

- hosts: all
  tasks:
  - name: Initialise kubernetes master
    shell:
      "kubeadm init --pod-network-cidr=192.168.112.0/20
      --apiserver-advertise-address={{ hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address'] }}
      --apiserver-cert-extra-sans={{ hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address'] }}"
    register: init

  - name: Display to screen
    debug:
      msg: "{{ init }}"

  - name: Create kube folder in vagrant home
    file:
      path: /root/.kube/
      state: directory
      owner: vagrant
      group: vagrant

  - name: Copy credentials to vagrant user
    file:
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      owner: vagrant
      group: vagrant
      state: link

  - name: Copy calico yaml
    copy:
      src: calico.yaml
      dest: /tmp/calico.yaml

  - name: Install pod network
    shell:  kubectl apply -f /tmp/calico.yaml

  - name: Create join script
    shell: kubeadm token create --print-join-command # >> /etc/kubeadm_join_cmd.sh
    register: join_cmd

  - name: Create join shell script
    copy:
      content: "{{ join_cmd.stdout }}"
      dest: /etc/kubeadm_join.sh

  - name: Copy join shell script to local
    local_action: copy content="{{ join_cmd.stdout }}" dest="./kubeadm_join.sh"