---
- import_playbook: common.yml

- hosts: all
  tasks:
  - name: Initialise kubernetes master
    shell: kubeadm init --apiserver-advertise-address=192.168.56.10  # static ip provided in vagrantfile
    register: init

  - name: Display to screen
    debug:
      msg: "{{ init }}"

  - name: Create kube folder in vagrant home
    file:
      path: /home/vagrant/.kube/
      state: directory
      owner: vagrant
      group: vagrant

  - name: Copy credentials to vagrant user
    file: 
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant
      state: link
    
  - name: Set KUBECONFIG env var
    shell: export KUBECONFIG=/etc/kubernetes/admin.conf

  - name: Install WaveWorks (CNI)
    become_user: vagrant
    shell:  kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')

  - name: Create join script
    become_user: vagrant
    shell: kubeadm token create --print-join-command # >> /etc/kubeadm_join_cmd.sh
    register: join_cmd
  
  - name: Create join shell script
    copy:
      content: "{{ join_cmd.stdout }}"
      dest: /etc/kubeadm_join.sh


